import { Knex } from 'knex';

exports.seed = function (knex: Knex) {
  return knex('users')
    .del()
    .then(function () {
      return knex('users').insert([
        // Actors
        {
          id: 1,
          name: 'Arun Chhetri',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 2,
          name: 'Chakra Dawadi',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 3,
          name: 'Khagendra Lamichhane',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 4,
          name: 'Kushal Panday',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 5,
          name: 'Sundar Dhital',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 6,
          name: 'Rajkamal Fakir',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 7,
          name: 'Sushil Sitaula',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 8,
          name: 'Reecha Sharma',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 9,
          name: 'Anup Neupane',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 10,
          name: 'Shishir Giri',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 11,
          name: 'Jeeban Bhattarai',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 12,
          name: 'Raj Thapa',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 13,
          name: 'Ghanashyam Joshi',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 14,
          name: 'Suraj Yadav',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 15,
          name: 'Lokendra Lekhak',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 16,
          name: 'Binod Neupane',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 17,
          name: 'Nikun Shrestha',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 18,
          name: 'Pravin Mandabya',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 19,
          name: 'Parikshit Bikram',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 20,
          name: 'Anooj Panday',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 21,
          name: 'Dipendra Shahi',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 22,
          name: 'Sulav Budhathoki',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 23,
          name: 'Arun Regmi',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 24,
          name: 'Bholaraj Sapkota',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 25,
          name: 'Sharad',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 26,
          name: 'Samrat',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 27,
          name: 'Nabin Mukti',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 28,
          name: 'Ayushman Desh Raj Joshi',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 29,
          name: 'Suman Koirala',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 30,
          name: 'Pawan Bhattarai',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 31,
          name: 'Sudan Munikar',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 32,
          name: 'Manil Neupane',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 33,
          name: 'Sajal Paudel',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 34,
          name: 'Roshan Murmu',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 35,
          name: 'Sunil Tamang',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 36,
          name: 'Prakash Ghimire',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 37,
          name: 'Prem',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 38,
          name: 'Jhotan Mehata',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 39,
          name: 'Kedar Nepal',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 40,
          name: 'Domi Kamat',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 41,
          name: 'Ghanendra Magar',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 42,
          name: 'Charman Munikar',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 43,
          name: 'Prajal Dulal',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 44,
          name: 'Kishor Anurag',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 45,
          name: 'Sabin Bhattrai',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 46,
          name: 'Geeta Koirala',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 47,
          name: 'Birendra Jha',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 48,
          name: 'Bharat',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 49,
          name: 'Prem Narayan Jha',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 50,
          name: 'Sushil Tamang',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 51,
          name: 'Dipak Kharel',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 52,
          name: 'Karan Basnet',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 53,
          name: 'Sagar Biswas',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 54,
          name: 'Ujjawal Rai',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 55,
          name: 'Anjali Shah',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 56,
          name: 'MK Subba',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 57,
          name: 'Biyal Rai',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 58,
          name: 'Anil Khadka',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 59,
          name: 'Arjun Acharya',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 60,
          name: 'J Adhikari (Rashmi Upreti)',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 61,
          name: 'J Adhikari (Laxmi Bardeba)',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        // Script Department
        {
          id: 70,
          department: 'Script',
          designation: 'Writer',
          name: 'Khagendra Lamichhane',
          role: 'user',
        },
        {
          id: 71,
          department: 'Script',
          designation: 'Writer',
          name: 'Yangesh Raj Pandit',
          role: 'user',
        },

        // Direction Unit
        {
          id: 72,
          department: 'Direction Unit',
          designation: 'Director',
          name: 'Lokesh Bajracharya',
          role: 'user',
        },
        {
          id: 73,
          department: 'Direction Unit',
          designation: '1st Asst. Director / Chief AD',
          name: 'Anil Khadka',
          role: 'user',
        },
        {
          id: 74,
          department: 'Direction Unit',
          designation: '2nd Asst. Director',
          name: 'Sourab Oli',
          role: 'user',
        },
        {
          id: 75,
          department: 'Direction Unit',
          designation: '3rd Asst. Director',
          name: 'Jeevan Dhungel',
          role: 'user',
        },
        {
          id: 76,
          department: 'Direction Unit',
          designation: '4th Asst. Director/Crowd Controller',
          name: 'Suraj Yadav',
          role: 'user',
        },
        {
          id: 77,
          department: 'Direction Unit',
          designation: '5th Asst. Director',
          name: 'Anita Syangbo',
          role: 'user',
        },
        {
          id: 707,
          department: 'Direction Unit',
          designation: '5th Asst. Director',
          name: 'Smriti Adhikari',
          role: 'user',
        },
        {
          id: 708,
          department: 'Direction Unit',
          designation: '5th Asst. Director',
          name: 'Subina Acharya',
          role: 'user',
        },
        {
          id: 78,
          department: 'Direction Unit',
          designation: 'Casting Director',
          name: 'Sanjog Rasaili',
          role: 'user',
        },
        {
          id: 79,
          department: 'Direction Unit',
          designation: 'Acting coach',
          name: 'Acting coach',
          role: 'user',
        },

        // Production Unit
        {
          id: 80,
          department: 'Production Unit',
          designation: 'Executive Producer',
          name: 'Sulav Budhathoki',
          role: 'user',
        },
        {
          id: 81,
          department: 'Production Unit',
          designation: 'Executive Producer',
          name: 'Medha Bhattarai',
          role: 'user',
        },
        {
          id: 82,
          department: 'Production Unit',
          designation: 'Producer 2',
          name: 'Khagendra Lamichhane',
          role: 'user',
        },
        {
          id: 83,
          department: 'Production Unit',
          designation: 'Co- Producer 1',
          name: 'Santosh Giri',
          role: 'user',
        },
        {
          id: 84,
          department: 'Production Unit',
          designation: 'Co- Producer 2',
          name: 'Sagar Kharel',
          role: 'user',
        },
        {
          id: 85,
          department: 'Production Unit',
          designation: 'Production Designer',
          name: 'Anjani Gajurel',
          role: 'user',
        },
        {
          id: 86,
          department: 'Production Unit',
          designation: 'Senior Art Director',
          name: 'Aashika Sharma',
          role: 'user',
        },
        {
          id: 87,
          department: 'Production Unit',
          designation: 'Art Director',
          name: 'Phanendra Bohara',
          role: 'user',
        },
        {
          id: 88,
          department: 'Production Unit',
          designation: 'Asst. 2',
          name: 'Sajan Bastakoti',
          role: 'user',
        },
        {
          id: 89,
          department: 'Production Unit',
          designation: 'Asst. 3',
          name: 'Prajwal Lamichhane',
          role: 'user',
        },
        {
          id: 90,
          department: 'Production Unit',
          designation: 'Assistant 4',
          name: 'Dhurba Karki',
          role: 'user',
        },
        {
          id: 91,
          department: 'Production Unit',
          designation: 'Production Manager',
          name: 'Arun Regmi',
          role: 'user',
        },
        {
          id: 92,
          department: 'Production Unit',
          designation: 'Asst. 1',
          name: 'Arjun Pokhrel',
          role: 'user',
        },
        {
          id: 93,
          department: 'Production Unit',
          designation: 'Asst. 2',
          name: 'Laxman Paudel',
          role: 'user',
        },
        {
          id: 94,
          department: 'Production Unit',
          designation: 'Local Manager',
          name: 'Mukesh Kumar Karna',
          role: 'user',
        },
        {
          id: 95,
          department: 'Production Unit',
          designation: 'Costume Designer',
          name: 'Alex Basukala',
          role: 'user',
        },
        {
          id: 96,
          department: 'Production Unit',
          designation: 'Costume Man 1',
          name: 'Devi Prasad Dahal',
          role: 'user',
        },
        {
          id: 97,
          department: 'Production Unit',
          designation: 'Costume Man 2',
          name: "Alex's Subordinate",
          role: 'user',
        },
        {
          id: 98,
          department: 'Production Unit',
          designation: 'Costume Man 3',
          name: "Alex's Intern",
          role: 'user',
        },
        {
          id: 99,
          department: 'Production Unit',
          designation: 'Make Up Artist (Package)',
          name: 'Samsher Tamang',
          role: 'user',
        },
        {
          id: 100,
          department: 'Production Unit',
          designation: 'Asst. 1',
          name: 'Bijaya Tamang',
          role: 'user',
        },
        {
          id: 101,
          department: 'Production Unit',
          designation: 'Asst. 2',
          name: 'Subhash Tamang',
          role: 'user',
        },
        {
          id: 102,
          department: 'Production Unit',
          designation: 'Hair Designer',
          name: 'Manju Kumari Thagunna',
          role: 'user',
        },
        {
          id: 103,
          department: 'Production Unit',
          designation: 'Indian Prosthetic Artist',
          name: 'Iyaz Sheikh',
          role: 'user',
        },
        {
          id: 104,
          department: 'Production Unit',
          designation: 'Spot Boy 1',
          name: 'Spot Boy 1',
          role: 'user',
        },
        {
          id: 105,
          department: 'Production Unit',
          designation: 'Spot Boy 2',
          name: 'Spot Boy 2',
          role: 'user',
        },
        {
          id: 106,
          department: 'Production Unit',
          designation: 'Spot Boy 3',
          name: 'Spot Boy 3',
          role: 'user',
        },
        {
          id: 107,
          department: 'Production Unit',
          designation: 'Spot Boy 4',
          name: 'Spot Boy 4',
          role: 'user',
        },
        {
          id: 108,
          department: 'Production Unit',
          designation: 'Spot Boy 5',
          name: 'Spot Boy 5',
          role: 'user',
        },

        // Camera Unit
        {
          id: 109,
          department: 'Camera Unit',
          designation: 'Cinematographer',
          name: 'Narendra Mainali',
          role: 'user',
        },
        {
          id: 110,
          department: 'Camera Unit',
          designation: 'Asst. Cinematographer',
          name: 'Rabi Roka',
          role: 'user',
        },
        {
          id: 111,
          department: 'Camera Unit',
          designation: 'Focus Puller',
          name: 'Ujan Kumar Bharati',
          role: 'user',
        },
        {
          id: 112,
          department: 'Camera Unit',
          designation: 'Gaffer',
          name: 'Bharat Prasad Nepal',
          role: 'user',
        },
        {
          id: 113,
          department: 'Camera Unit',
          designation: 'Assistant Gaffer',
          name: 'Sundar Shrestha',
          role: 'user',
        },
        {
          id: 114,
          department: 'Camera Unit',
          designation: 'Light Man 1',
          name: 'Narayan Upreti',
          role: 'user',
        },
        {
          id: 115,
          department: 'Camera Unit',
          designation: 'Light Man 2',
          name: 'Govind Thapa',
          role: 'user',
        },
        {
          id: 116,
          department: 'Camera Unit',
          designation: 'Light Man 3',
          name: 'Uday Raj Majhi',
          role: 'user',
        },
        {
          id: 117,
          department: 'Camera Unit',
          designation: 'Light Man 5',
          name: 'Light Man 5',
          role: 'user',
        },
        {
          id: 118,
          department: 'Camera Unit',
          designation: 'Trolley Boy',
          name: 'Trolley Boy',
          role: 'user',
        },
        {
          id: 119,
          department: 'Camera Unit',
          designation: 'Crane Boy 1',
          name: 'Rajiv Chhetri',
          role: 'user',
        },
        {
          id: 120,
          department: 'Camera Unit',
          designation: 'Crane Boy 2',
          name: 'Crane Boy 2',
          role: 'user',
        },
        {
          id: 121,
          department: 'Camera Unit',
          designation: 'Asst. Cinematographer',
          name: 'Ashish Basnet',
          role: 'user',
        },
        {
          id: 122,
          department: 'Production Unit',
          designation: 'Asst. 2',
          name: 'Bishnu',
          role: 'user',
        },
        {
          id: 123,
          department: 'Production Unit',
          designation: 'Asst. 2',
          name: 'Krishna Tamang',
          role: 'user',
        },

        // VFX Unit
        {
          id: 125,
          department: 'VFX Unit',
          designation: 'VFX Supervisor 1',
          name: 'Pukar Dhimal',
          role: 'user',
        },
        {
          id: 126,
          department: 'VFX Unit',
          designation: 'VFX Supervisor 1',
          name: 'Bikram Gurung',
          role: 'user',
        },

        // Action Unit
        {
          id: 127,
          department: 'Action Unit',
          designation: 'Action Director',
          name: 'Rajkumar Upreti',
          role: 'user',
        },
        {
          id: 128,
          department: 'Action Unit',
          designation: 'Assistant 1',
          name: 'Assistant 1',
          role: 'user',
        },
        {
          id: 129,
          department: 'Action Unit',
          designation: 'Assistant 2',
          name: 'Assistant 2',
          role: 'user',
        },

        // Editor on Set / Data Wrangler
        {
          id: 130,
          department: 'Editor on Set',
          designation: 'Editor',
          name: 'Rabin Shrestha',
          role: 'user',
        },
        {
          id: 131,
          department: 'Editor on Set',
          designation: 'Asst. Editor',
          name: 'Dinesh Kafle',
          role: 'user',
        },
        {
          id: 132,
          department: 'Editor on Set',
          designation: 'Data Wrangler',
          name: 'Data Wrangler',
          role: 'user',
        },

        // Sound Unit
        {
          id: 133,
          department: 'Sound Unit',
          designation: 'Location Sound Recordist',
          name: 'Sagar Ghimire (Ghan Kumar Ghimire)',
          role: 'user',
        },
        {
          id: 134,
          department: 'Sound Unit',
          designation: 'Asst. 1',
          name: 'Assistant 1',
          role: 'user',
        },
        {
          id: 135,
          department: 'Sound Unit',
          designation: 'Asst. 2',
          name: 'Assistant 2',
          role: 'user',
        },

        // BTS Unit
        {
          id: 136,
          department: 'BTS Unit',
          designation: 'BTS 1',
          name: 'Bibek Timalsina',
          role: 'user',
        },
        {
          id: 137,
          department: 'BTS Unit',
          designation: 'BTS 2',
          name: 'BTS 2',
          role: 'user',
        },
        {
          id: 138,
          department: 'BTS Unit',
          designation: 'BTS 3',
          name: 'BTS 3',
          role: 'user',
        },
        {
          id: 139,
          department: 'Security Unit',
          designation: 'Security man 1',
          name: 'Security man 1',
          role: 'user',
        },
        {
          id: 140,
          department: 'Security Unit',
          designation: 'Security man 2',
          name: 'Security man 2',
          role: 'user',
        },
        {
          id: 200,
          name: "S. ADHIKARI (LAXMI'S SON)",
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 201,
          name: 'L. NEPAL (SAMRIDDHI NEPAL)',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 202,
          name: 'B. ADHIKARI (BIKASH JOSHI)',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 203,
          name: 'H. NEPAL (MILAN KARKI)',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 204,
          name: 'M. SIWAKOTI',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 205,
          name: 'N. KOIRALA (BENU CHUDAL, DAMAK)',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 206,
          name: 'LAXMI SIGDEL',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 207,
          name: 'P. BHATTRAI (MJ MITHUN, GT)',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 208,
          name: 'GOPAL KRITI, GT',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 209,
          name: 'SANDEEP DANGOL, KTM',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 210,
          name: 'INDRA BAHADUR PARIYAR, BRT',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 211,
          name: 'Surendra Thapa',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 212,
          name: 'SURAJ MAJHI',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 213,
          name: 'Woner LAW Ghimire',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 214,
          name: 'RAJESH CHAUDHARI',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 215,
          name: 'SURENDRA THAPA',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 216,
          name: 'SUSHIL KARKI',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 217,
          name: 'Niraj Black',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 218,
          name: 'Woner Lama Ghimire',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 219,
          name: 'Rajesh Chaudhary',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 220,
          name: 'MUNNA SAHANI',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 221,
          name: 'PARAS RAJBANSI',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 222,
          name: 'PRAMOD YADAV',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 223,
          name: 'RAKESH RAJBANSI',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 224,
          name: 'MUKESH KARNA',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 225,
          name: 'HIMAL NIRAULA',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 226,
          name: 'DEVID BISTA',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 227,
          name: 'LOKESH DANGOL',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 228,
          name: 'BIBEK MISHRA',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 229,
          name: 'MAHESH BUDHATHOKI',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 230,
          name: 'BIBEK RAUT',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 231,
          name: 'PRADIP SHRESTHA',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 232,
          name: 'DEVENDRA RAJBANSH',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 233,
          name: 'RAJESH THAKUR',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 234,
          name: 'PRAVIN BHANDARI',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 235,
          name: 'NAVIN RIJAL',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 236,
          name: 'DIPAK NIRAULA',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 237,
          name: 'RADHA CHAUDHAR',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 238,
          name: 'MADHU SHAH',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 239,
          name: 'MANTOSH',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        {
          id: 240,
          name: 'SUDIP JUNG KARKI',
          designation: 'Actor',
          department: 'Casting Department',
          role: 'user',
        },
        ...Array.from({ length: 30 }, (v, i) => ({
          id: 150 + i,
          name: `Visitor ${i + 1}`,
          designation: `Visitor ${i + 1}`,
          department: 'Visitors',
          role: 'user',
        })),
        // admin and manager
        {
          id: 500,
          name: 'Samir Alam',
          email: 'samir@gmail.com',
          password: '3c5f6daf0e3a10f320334913ff9ae48e9b769f11a5330bd8cb86a9abb94f78a0', // samir@123
          designation: 'Writer',
          department: 'Script',
          role: 'admin',
        },
        {
          id: 501,
          name: 'Santosh Giri',
          email: 'santoshgiri@gmail.com',
          password: '7676aaafb027c825bd9abab78b234070e702752f625b752e55e55b48e607e358', //admin@123
          designation: 'Writer',
          department: 'Script',
          role: 'admin',
        },
        {
          id: 502,
          name: 'Cafe Manager',
          email: 'manager@gmail.com',
          password: '324d52ea400e79ae65163f0b369e295c4993d26204c66317ee8e53f31ae003e3', // manager@123
          designation: 'Writer',
          department: 'Script',
          role: 'manager',
        },
        {
          id: 503,
          name: 'admin',
          email: 'admin@gmail.com',
          password: 'd8ec9b20f8519604e1b6d4bdfcd43db2730a9408c6ae2cd6f8cef70f1b10250a', // bibek1234
          designation: 'Writer',
          department: 'Script',
          role: 'admin',
        },
      ]);
    });
};
